import swaggerJsdoc from 'swagger-jsdoc'

const PORT = process.env.PORT || 3000

const options = {
  definition: {
    openapi: '3.0.3',
    info: {
      title: 'Kandew API',
      version: '1.0.0',
      description:
        'REST API for the Kandew team task board. All endpoints except `POST /api/auth/login` require a bearer JWT.',
      contact: { name: 'Kandew' },
    },
    servers: [{ url: `http://localhost:${PORT}`, description: 'Local development' }],
    tags: [
      { name: 'Auth', description: 'Authentication endpoints' },
      { name: 'Teams', description: 'Team management and membership' },
      { name: 'Tasks', description: 'Task board operations (kanban cards)' },
      { name: 'Comments', description: 'Task comments' },
    ],
    components: {
      securitySchemes: {
        bearerAuth: { type: 'http', scheme: 'bearer', bearerFormat: 'JWT' },
      },
      schemas: {
        Error: {
          type: 'object',
          required: ['error'],
          properties: { error: { type: 'string' } },
          example: { error: 'Not a member of this team' },
        },
        Message: {
          type: 'object',
          required: ['message'],
          properties: { message: { type: 'string' } },
          example: { message: 'Task deleted successfully' },
        },
        LoginRequest: {
          type: 'object',
          required: ['email', 'password'],
          properties: {
            email: { type: 'string', format: 'email' },
            password: { type: 'string', format: 'password' },
          },
          example: { email: 'alice@example.com', password: 'hunter2' },
        },
        LoginResponse: {
          type: 'object',
          properties: {
            token: { type: 'string', description: 'JWT bearer token' },
            user: {
              type: 'object',
              properties: {
                id: { type: 'integer' },
                username: { type: 'string' },
                email: { type: 'string', format: 'email' },
              },
            },
          },
          example: {
            token: 'eyJhbGciOi...<jwt>',
            user: { id: 42, username: 'alice', email: 'alice@example.com' },
          },
        },
        Team: {
          type: 'object',
          properties: {
            id: { type: 'integer' },
            name: { type: 'string' },
            icon: { type: 'string', nullable: true },
            creator_user_id: { type: 'integer' },
            petal_value: { type: 'number', format: 'float', default: 1.0 },
            created_at: { type: 'string', format: 'date-time' },
            current_user_role: {
              type: 'string',
              enum: ['owner', 'admin', 'member'],
              description: "Role of the authenticated caller — present on list/get responses.",
            },
          },
          example: {
            id: 1,
            name: 'Core Platform',
            icon: 'https://picsum.photos/seed/core/80/80',
            creator_user_id: 42,
            petal_value: 2.5,
            created_at: '2026-04-01T09:15:00Z',
            current_user_role: 'owner',
          },
        },
        TeamCreate: {
          type: 'object',
          required: ['name'],
          properties: {
            name: { type: 'string' },
            icon: { type: 'string', nullable: true },
          },
          example: { name: 'Design Sprint', icon: 'https://picsum.photos/seed/design/80/80' },
        },
        TeamUpdate: {
          type: 'object',
          description: 'Any subset of mutable team fields.',
          properties: {
            name: { type: 'string' },
            icon: { type: 'string', nullable: true },
            petal_value: { type: 'number', format: 'float' },
          },
          example: { name: 'Core Platform (renamed)', petal_value: 3.0 },
        },
        Member: {
          type: 'object',
          properties: {
            id: { type: 'integer', description: 'User id' },
            username: { type: 'string' },
            email: { type: 'string', format: 'email' },
            avatar: { type: 'string', nullable: true },
            role: { type: 'string', enum: ['owner', 'admin', 'member'] },
            petals_earned: { type: 'integer' },
            money_earned: {
              type: 'string',
              description: 'petals_earned × team.petal_value, formatted to 2 decimals.',
            },
          },
          example: {
            id: 42,
            username: 'alice',
            email: 'alice@example.com',
            avatar: 'https://picsum.photos/seed/alice/80/80',
            role: 'owner',
            petals_earned: 18,
            money_earned: '45.00',
          },
        },
        InviteMemberRequest: {
          type: 'object',
          required: ['email'],
          properties: { email: { type: 'string', format: 'email' } },
          example: { email: 'newbie@example.com' },
        },
        Comment: {
          type: 'object',
          properties: {
            id: { type: 'integer' },
            task_id: { type: 'integer' },
            author_user_id: { type: 'integer' },
            author_name: { type: 'string' },
            author_avatar: { type: 'string', nullable: true },
            body: { type: 'string' },
            created_at: { type: 'string', format: 'date-time' },
            updated_at: { type: 'string', format: 'date-time', nullable: true },
          },
          example: {
            id: 77,
            task_id: 12,
            author_user_id: 42,
            author_name: 'alice',
            author_avatar: 'https://picsum.photos/seed/alice/80/80',
            body: 'Looks good — ready for review.',
            created_at: '2026-04-10T14:22:00Z',
            updated_at: null,
          },
        },
        CommentBody: {
          type: 'object',
          required: ['body'],
          properties: { body: { type: 'string' } },
          example: { body: 'Updated the copy based on design review.' },
        },
        Task: {
          type: 'object',
          properties: {
            id: { type: 'integer' },
            title: { type: 'string' },
            description: { type: 'string' },
            priority: { type: 'string', enum: ['low', 'medium', 'high'] },
            column_id: { type: 'string', enum: ['todo', 'in-progress', 'review', 'done'] },
            team_id: { type: 'integer' },
            assignee_user_id: { type: 'integer', nullable: true },
            assignee_name: { type: 'string', nullable: true },
            assignee_avatar: { type: 'string', nullable: true },
            creator_user_id: { type: 'integer' },
            max_petals: { type: 'integer' },
            earned_petals: { type: 'integer', nullable: true },
            review_entered_at: { type: 'string', format: 'date-time', nullable: true },
            frozen_petals_at_review: { type: 'integer', nullable: true },
            due_date: { type: 'string', format: 'date-time', nullable: true },
            completed_at: { type: 'string', format: 'date-time', nullable: true },
            created_at: { type: 'string', format: 'date-time' },
            sort_order: { type: 'integer' },
          },
          example: {
            id: 12,
            title: 'Wire up petal earnings on task completion',
            description: 'When a task moves to done, award frozen petals to the assignee.',
            priority: 'high',
            column_id: 'in-progress',
            team_id: 1,
            assignee_user_id: 42,
            assignee_name: 'alice',
            assignee_avatar: 'https://picsum.photos/seed/alice/80/80',
            creator_user_id: 17,
            max_petals: 5,
            earned_petals: null,
            review_entered_at: null,
            frozen_petals_at_review: null,
            due_date: '2026-04-20T00:00:00Z',
            completed_at: null,
            created_at: '2026-04-02T10:00:00Z',
            sort_order: 3,
          },
        },
        TaskCreate: {
          type: 'object',
          required: ['title', 'description'],
          properties: {
            title: { type: 'string' },
            description: { type: 'string' },
            priority: { type: 'string', enum: ['low', 'medium', 'high'], default: 'medium' },
            columnId: {
              type: 'string',
              enum: ['todo', 'in-progress', 'review', 'done'],
              default: 'todo',
            },
            assigneeUserId: { type: 'integer', nullable: true },
            maxPetals: { type: 'integer', default: 5 },
            dueDate: { type: 'string', format: 'date-time', nullable: true },
          },
          example: {
            title: 'Ship beta release',
            description: 'Tag v0.1.0 and cut release notes.',
            priority: 'high',
            columnId: 'todo',
            assigneeUserId: 42,
            maxPetals: 8,
            dueDate: '2026-04-25T00:00:00Z',
          },
        },
        TaskUpdate: {
          type: 'object',
          description:
            'Any subset of fields. Move fields (columnId/sortOrder/reviewEnteredAt/frozenPetalsAtReview/completedAt/earnedPetals) are allowed for any team member. Edit fields (title/description/priority/assigneeUserId/maxPetals/dueDate) require the owner role.',
          properties: {
            title: { type: 'string' },
            description: { type: 'string' },
            priority: { type: 'string', enum: ['low', 'medium', 'high'] },
            columnId: { type: 'string', enum: ['todo', 'in-progress', 'review', 'done'] },
            assigneeUserId: { type: 'integer', nullable: true },
            maxPetals: { type: 'integer' },
            dueDate: { type: 'string', format: 'date-time', nullable: true },
            earnedPetals: { type: 'integer' },
            reviewEnteredAt: { type: 'string', format: 'date-time', nullable: true },
            frozenPetalsAtReview: { type: 'integer', nullable: true },
            completedAt: { type: 'string', format: 'date-time', nullable: true },
            sortOrder: { type: 'integer' },
          },
          example: { columnId: 'review', sortOrder: 0, reviewEnteredAt: '2026-04-12T16:00:00Z' },
        },
      },
    },
    security: [{ bearerAuth: [] }],
  },
  apis: ['./src/routes/*.js', './src/routes/**/*.js'],
}

export const swaggerSpec = swaggerJsdoc(options)
